### PR TITLE
Add new audio tasks

### PR DESCRIPTION
**Pull request by mpgxvii**
- Add new audio tasks for the lung study: `audio_count` and`audio_vocalisation`

### CODE REVIEW

**Comment by mpgxvii** [comment]
@yatharthranjan Also, I just realized the voice sampling tasks (without free speech) have already been added:
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted 
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted_2
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted_3

**Comment by yatharthranjan** [comment]
Yeah, I remember those from Val's study I think.

**Review by yatharthranjan — COMMENTED** [review]
Hi, thanks for adding these so quickly, the vocalisation tasks are one task so should be in a single questionnaire.

**Comment by mpgxvii** [comment]
> Hi, thanks for adding these so quickly, the vocalisation tasks are one task so should be in a single questionnaire.

Sorry about that I got confused. I've made the changes now.

**Review by yatharthranjan — APPROVED** [review]
Thanks. LGTM. It would be great if @afolarin, you can review too.

**Review by afolarin — APPROVED** [review]

**Comment by yatharthranjan** [comment]
> @yatharthranjan Also, I just realized the voice sampling tasks (without free speech) have already been added:
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted_2
https://github.com/RADAR-base/RADAR-REDCap-aRMT-Definitions/tree/master/questionnaires/audio_without_unscripted_3

@mpgxvii just looking at these now, is there a reason they are separate tasks? They don't seem big enough and should be comfortable to complete in a single go. Maybe we should combine these 3 excerpts from the Northwind into a single questionnaire for RALPMH. What do you think @mpgxvii and @afolarin? Just asking since we already have 2 other audio tasks in RALPMH.

**Comment by afolarin** [comment]
I think we should combine the 3x excerps into one for this (*I think @nickcummins41 did originally have this combined but was split to minimise training effect) but for RALPMH this is relatively short data collection so we'd not get many repeats, so better probably to get a single larger sample.

**Comment by mpgxvii** [comment]
@afolarin @yatharthranjan Okay I see. Yes the CNS MDD version had this separated into 3 excerpts because it was scheduled every 2 weeks but the MS version only had this every 6 weeks so it was combined. I can make the changes for the combined audio task.

**Comment by yatharthranjan** [comment]
Amazing, Thank you both.

**Comment by nickcummins41** [comment]
> I think we should combine the 3x excerps into one for this (*I think @nickcummins41 did originally have this combined but was split to minimise training effect) but for RALPMH this is relatively short data collection so we'd not get many repeats, so better probably to get a single larger sample.

Yep - this is all correct :-)

**Pull request merged**
