### PR TITLE
Add COVID-19 CNS questionnaires

### PR DESCRIPTION
**Pull request by mpgxvii**
- Add COVID-19 CNS questionnaires (1 baseline once, 1 followup every 2 weeks)

### CODE REVIEW

**Comment by mpgxvii** [comment]
@afolarin @yatharthranjan I'm not sure how we can schedule the baseline questionnaire since the questionnaires are scheduled based on enrolment?

**Comment by afolarin** [comment]
Schedule once then at 10yrs ahead for the next one?

**Comment by mpgxvii** [comment]
For existing participants, since they all have different enrolment dates, it would be difficult to schedule one all at the same time because the questionnaire would be scheduled at an offset from the enrolment date. We can maybe add it to the clinical tasks page or add support for it which I have in a PR https://github.com/RADAR-base/RADAR-Questionnaire/pull/933 ?

**Comment by afolarin** [comment]
> For existing participants, since they all have different enrolment dates, it would be difficult to schedule one all at the same time because the questionnaire would be scheduled at an offset from the enrolment date. We can maybe add it to the clinical tasks page or add support for it which I have in a PR [RADAR-base/RADAR-Questionnaire#933](https://github.com/RADAR-base/RADAR-Questionnaire/pull/933) ?

I think this is fine, this is a 2wk repeat questionnaire so don't need to worry about this, In fact, I don't think that is what they want or need.

**Pull request merged**
