### PR TITLE
Update NSHD questionnaire

### PR DESCRIPTION
**Pull request by mpgxvii**
- Update `chair_rises` questionnaire

### CODE REVIEW

**Comment by afolarin** [comment]
there also seems a broken image link above the Chair Rises instruction video. 
Screenshot_20220915-154717

**Review by afolarin — APPROVED** [review]
LGTM :+1:

**Comment by mpgxvii** [comment]
> there also seems a broken image link above the Chair Rises instruction video. Screenshot_20220915-154717

Ah yes, this is because I just used the Redcap image link when I uploaded the image. Where could we host the images instead?

**Comment by afolarin** [comment]
could setup an AWS bucket?

**Comment by yatharthranjan** [comment]
Yes a public S3 bucket would be fine

**Review by yatharthranjan — APPROVED** [review]
LGTM

**Pull request merged**
