### PR TITLE
Add CNS COVID19 Followup V2 questionnaire

### PR DESCRIPTION
**Pull request by mpgxvii**
- Add `cns_covid19_followup_v2` questionnaire, modified version of the `cns_covid19_followup` questionnaire
- This adds 6 new questions

### CODE REVIEW

**Comment by mpgxvii** [comment]
@afolarin I initially thought it would just be 2 additional questions, but there were some branching questions so there are 6 new questions in total, so I guess adding it as a separate questionnaire would be better?

**Comment by afolarin** [comment]
you mean to replace the existing questionnaire with one with the new questionnaires or adding the 6 questions on a new additional questionnaire?

**Comment by mpgxvii** [comment]
> you mean to replace the existing questionnaire with one with the new questionnaires or adding the 6 questions on a new additional questionnaire?

On a new additional questionnaire.

**Comment by afolarin** [comment]
What's the requirement for a named version, presumably they are already versioned in this repo? Unless you need both v1 and v2 in play simultaneously (or am I missing something)

**Comment by yatharthranjan** [comment]
> What's the requirement for a named version, presumably they are already versioned in this repo? Unless you need both v1 and v2 in play simultaneously (or am I missing something)

I think this is more to create a clear separation, we could use the same name but we are also going to update the topic name (to help analysis and avoid inconsistencies experienced in the past with this type of transition in the data), so it's for the sake of consistency with the topic.

**Comment by afolarin** [comment]
> I think this is more to create a clear separation, we could use the same name but we are also going to update the topic name (to help analysis and avoid inconsistencies experienced in the past with this type of transition in the data), so it's for the sake of consistency with the topic.

OK i see. So the idea is we'll have new questionnaires_version for each update to a questionnaire (this will result in a proliferation of questionnaires on the repo) -- updating the questionnaire is quite a common (though undesirable) thing, but people do love changing the questionnaires on live projects. 

What about keeping the same questionnaire name tagging the commit with `_version` on github, keeping the same names but giving a `_version` suffix or something to the topic name?

**But I'm happy to defer to you guys** -- however, we should work out how best to proceed in a standard way in the future?

**Comment by yatharthranjan** [comment]
I think the important thing is keeping the topic name different, from a questionnaire standpoint, I am happy for you guys to decide. 

I agree for minute changes this should not be a new questionnaire. However, I do think a significant change to a questionnaire should warrant a new version (we can specify the version as you suggested) -- or similar to how we did with ESM (28q).

**Comment by afolarin** [comment]
> I agree for minute changes this should not be a new questionnaire. However, I do think a significant change to a questionnaire should warrant a new version (we can specify the version as you suggested) -- or similar to how we did with ESM (28q).

yes, agreed. Is there a defined cutoff when we should do a new questionnaire? e.g. say adding and modifying new fields = new version, deleting fields or minor changes to the text = same questionnaire?

**Comment by mpgxvii** [comment]
Yes, I thought this would be similar to ESM28q.

So far, the changes we've made to live (or already released) questionnaires were mostly translation changes and minor option label modifications. Major changes were done when the questionnaires were not yet released to participants (though already in this repo). I don't think we've had to add new questions to an already live questionnaire aside from the ESM->ESM28q. So maybe we can stick to that standard?

**Comment by mpgxvii** [comment]
> yes, agreed. Is there a defined cutoff when we should do a new questionnaire? e.g. say adding and modifying new fields = new version, deleting fields or minor changes to the text = same questionnaire?

Yes, I agree. Also, if there are new choices/options to existing fields = new version. Changing the labels of choices/options = same questionnaire.

**Comment by afolarin** [comment]
OK LGTM!

**Pull request merged**
